from django.urls import path
from .views import (
    DashboardHomeView,
    DashboardLoginView,
    dashboard_logout_view,
    PartnerListView,
    PartnerCreateView,
    PartnerUpdateView,
    PartnerDeleteView,
    CategoryListView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    DocumentListView,
    DocumentCreateView,
    DocumentUpdateView,
    DocumentDeleteView,
    EventListView,
    EventCreateView,
    EventUpdateView,
    EventDeleteView,
    MediaEventListView,
    MediaEventCreateView,
    MediaEventUpdateView,
    MediaEventDeleteView,
    MediaEventPhotosView,
    MediaPhotoUploadView,
    MediaPhotoDeleteView,
    DashboardNewsListView,
    DashboardNewsCreateView,
    DashboardNewsUpdateView,
    DashboardNewsDeleteView,
    ProjectCategoryListView,
    ProjectCategoryCreateView,
    ProjectCategoryUpdateView,
    ProjectCategoryDeleteView,
    DashboardProjectListView,
    DashboardProjectCreateView,
    DashboardProjectUpdateView,
    DashboardProjectDeleteView,
    PersonListView,
    PersonCreateView,
    PersonUpdateView,
    PersonDeleteView,
    SeasonListView,
    SeasonCreateView,
    SeasonUpdateView,
    SeasonDeleteView,
    TeamMemberListView,
    TeamMemberCreateView,
    TeamMemberUpdateView,
    TeamMemberDeleteView,
    CoachListView,
    CoachCreateView,
    CoachUpdateView,
    CoachDeleteView,
    JudgeListView,
    JudgeCreateView,
    JudgeUpdateView,
    JudgeDeleteView,
)

app_name = "dashboard"

urlpatterns = [
    path("login/", DashboardLoginView.as_view(), name="login"),
    path("logout/", dashboard_logout_view, name="logout"),
    path("", DashboardHomeView.as_view(), name="index"),

    path("partners/", PartnerListView.as_view(), name="partner_list"),
    path("partners/create/", PartnerCreateView.as_view(), name="partner_create"),
    path("partners/<int:pk>/edit/", PartnerUpdateView.as_view(), name="partner_update"),
    path("partners/<int:pk>/delete/", PartnerDeleteView.as_view(), name="partner_delete"),

    path("documents/categories/", CategoryListView.as_view(), name="category_list"),
    path("documents/categories/create/", CategoryCreateView.as_view(), name="category_create"),
    path("documents/categories/<int:pk>/edit/", CategoryUpdateView.as_view(), name="category_update"),
    path("documents/categories/<int:pk>/delete/", CategoryDeleteView.as_view(), name="category_delete"),
    path("documents/", DocumentListView.as_view(), name="document_list"),
    path("documents/create/", DocumentCreateView.as_view(), name="document_create"),
    path("documents/<int:pk>/edit/", DocumentUpdateView.as_view(), name="document_update"),
    path("documents/<int:pk>/delete/", DocumentDeleteView.as_view(), name="document_delete"),

    path("calendar/", EventListView.as_view(), name="event_list"),
    path("calendar/create/", EventCreateView.as_view(), name="event_create"),
    path("calendar/<int:pk>/edit/", EventUpdateView.as_view(), name="event_update"),
    path("calendar/<int:pk>/delete/", EventDeleteView.as_view(), name="event_delete"),

    path("media/", MediaEventListView.as_view(), name="media_event_list"),
    path("media/create/", MediaEventCreateView.as_view(), name="media_event_create"),
    path("media/<int:pk>/edit/", MediaEventUpdateView.as_view(), name="media_event_update"),
    path("media/<int:pk>/delete/", MediaEventDeleteView.as_view(), name="media_event_delete"),
    path("media/<int:pk>/photos/", MediaEventPhotosView.as_view(), name="media_event_photos"),
    path("media/<int:pk>/photos/upload/", MediaPhotoUploadView.as_view(), name="media_photo_upload"),
    path("media/<int:pk>/photos/<int:photo_pk>/delete/", MediaPhotoDeleteView.as_view(), name="media_photo_delete"),

    path("news/", DashboardNewsListView.as_view(), name="news_list"),
    path("news/create/", DashboardNewsCreateView.as_view(), name="news_create"),
    path("news/<int:pk>/edit/", DashboardNewsUpdateView.as_view(), name="news_update"),
    path("news/<int:pk>/delete/", DashboardNewsDeleteView.as_view(), name="news_delete"),

    path("projects/categories/", ProjectCategoryListView.as_view(), name="project_category_list"),
    path("projects/categories/create/", ProjectCategoryCreateView.as_view(), name="project_category_create"),
    path("projects/categories/<int:pk>/edit/", ProjectCategoryUpdateView.as_view(), name="project_category_update"),
    path("projects/categories/<int:pk>/delete/", ProjectCategoryDeleteView.as_view(), name="project_category_delete"),

    path("projects/", DashboardProjectListView.as_view(), name="project_list"),
    path("projects/create/", DashboardProjectCreateView.as_view(), name="project_create"),
    path("projects/<int:pk>/edit/", DashboardProjectUpdateView.as_view(), name="project_update"),
    path("projects/<int:pk>/delete/", DashboardProjectDeleteView.as_view(), name="project_delete"),

    path("structure/", PersonListView.as_view(), name="person_list"),
    path("structure/create/", PersonCreateView.as_view(), name="person_create"),
    path("structure/<int:pk>/edit/", PersonUpdateView.as_view(), name="person_update"),
    path("structure/<int:pk>/delete/", PersonDeleteView.as_view(), name="person_delete"),

    path("teams/seasons/", SeasonListView.as_view(), name="season_list"),
    path("teams/seasons/create/", SeasonCreateView.as_view(), name="season_create"),
    path("teams/seasons/<int:pk>/edit/", SeasonUpdateView.as_view(), name="season_update"),
    path("teams/seasons/<int:pk>/delete/", SeasonDeleteView.as_view(), name="season_delete"),

    path("teams/members/", TeamMemberListView.as_view(), name="team_member_list"),
    path("teams/members/create/", TeamMemberCreateView.as_view(), name="team_member_create"),
    path("teams/members/<int:pk>/edit/", TeamMemberUpdateView.as_view(), name="team_member_update"),
    path("teams/members/<int:pk>/delete/", TeamMemberDeleteView.as_view(), name="team_member_delete"),

    path("teams/coaches/", CoachListView.as_view(), name="coach_list"),
    path("teams/coaches/create/", CoachCreateView.as_view(), name="coach_create"),
    path("teams/coaches/<int:pk>/edit/", CoachUpdateView.as_view(), name="coach_update"),
    path("teams/coaches/<int:pk>/delete/", CoachDeleteView.as_view(), name="coach_delete"),

    path("teams/judges/", JudgeListView.as_view(), name="judge_list"),
    path("teams/judges/create/", JudgeCreateView.as_view(), name="judge_create"),
    path("teams/judges/<int:pk>/edit/", JudgeUpdateView.as_view(), name="judge_update"),
    path("teams/judges/<int:pk>/delete/", JudgeDeleteView.as_view(), name="judge_delete"),
]