from django.urls import path
from .views import (
    DashboardHomeView,
    DashboardLoginView,
    dashboard_logout_view,
    PartnerListView,
    PartnerCreateView,
    PartnerUpdateView,
    PartnerDeleteView,
    CategoryListView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    DocumentListView,
    DocumentCreateView,
    DocumentUpdateView,
    DocumentDeleteView,
    EventListView,
    EventCreateView,
    EventUpdateView,
    EventDeleteView,
    MediaEventListView,
    MediaEventCreateView,
    MediaEventUpdateView,
    MediaEventDeleteView,
    MediaEventPhotosView,
    MediaPhotoUploadView,
    MediaPhotoDeleteView,
    DashboardNewsListView,
    DashboardNewsCreateView,
    DashboardNewsUpdateView,
    DashboardNewsDeleteView,
    ProjectCategoryListView,
    ProjectCategoryCreateView,
    ProjectCategoryUpdateView,
    ProjectCategoryDeleteView,
    DashboardProjectListView,
    DashboardProjectCreateView,
    DashboardProjectUpdateView,
    DashboardProjectDeleteView,
)

app_name = "dashboard"

urlpatterns = [
    path("login/", DashboardLoginView.as_view(), name="login"),
    path("logout/", dashboard_logout_view, name="logout"),
    path("", DashboardHomeView.as_view(), name="index"),

    path("partners/", PartnerListView.as_view(), name="partner_list"),
    path("partners/create/", PartnerCreateView.as_view(), name="partner_create"),
    path("partners/<int:pk>/edit/", PartnerUpdateView.as_view(), name="partner_update"),
    path("partners/<int:pk>/delete/", PartnerDeleteView.as_view(), name="partner_delete"),

    path("documents/categories/", CategoryListView.as_view(), name="category_list"),
    path("documents/categories/create/", CategoryCreateView.as_view(), name="category_create"),
    path("documents/categories/<int:pk>/edit/", CategoryUpdateView.as_view(), name="category_update"),
    path("documents/categories/<int:pk>/delete/", CategoryDeleteView.as_view(), name="category_delete"),
    path("documents/", DocumentListView.as_view(), name="document_list"),
    path("documents/create/", DocumentCreateView.as_view(), name="document_create"),
    path("documents/<int:pk>/edit/", DocumentUpdateView.as_view(), name="document_update"),
    path("documents/<int:pk>/delete/", DocumentDeleteView.as_view(), name="document_delete"),

    path("calendar/", EventListView.as_view(), name="event_list"),
    path("calendar/create/", EventCreateView.as_view(), name="event_create"),
    path("calendar/<int:pk>/edit/", EventUpdateView.as_view(), name="event_update"),
    path("calendar/<int:pk>/delete/", EventDeleteView.as_view(), name="event_delete"),

    path("media/", MediaEventListView.as_view(), name="media_event_list"),
    path("media/create/", MediaEventCreateView.as_view(), name="media_event_create"),
    path("media/<int:pk>/edit/", MediaEventUpdateView.as_view(), name="media_event_update"),
    path("media/<int:pk>/delete/", MediaEventDeleteView.as_view(), name="media_event_delete"),
    path("media/<int:pk>/photos/", MediaEventPhotosView.as_view(), name="media_event_photos"),
    path("media/<int:pk>/photos/upload/", MediaPhotoUploadView.as_view(), name="media_photo_upload"),
    path("media/<int:pk>/photos/<int:photo_pk>/delete/", MediaPhotoDeleteView.as_view(), name="media_photo_delete"),

    path("news/", DashboardNewsListView.as_view(), name="news_list"),
    path("news/create/", DashboardNewsCreateView.as_view(), name="news_create"),
    path("news/<int:pk>/edit/", DashboardNewsUpdateView.as_view(), name="news_update"),
    path("news/<int:pk>/delete/", DashboardNewsDeleteView.as_view(), name="news_delete"),

    path("projects/categories/", ProjectCategoryListView.as_view(), name="project_category_list"),
    path("projects/categories/create/", ProjectCategoryCreateView.as_view(), name="project_category_create"),
    path("projects/categories/<int:pk>/edit/", ProjectCategoryUpdateView.as_view(), name="project_category_update"),
    path("projects/categories/<int:pk>/delete/", ProjectCategoryDeleteView.as_view(), name="project_category_delete"),

    path("projects/", DashboardProjectListView.as_view(), name="project_list"),
    path("projects/create/", DashboardProjectCreateView.as_view(), name="project_create"),
    path("projects/<int:pk>/edit/", DashboardProjectUpdateView.as_view(), name="project_update"),
    path("projects/<int:pk>/delete/", DashboardProjectDeleteView.as_view(), name="project_delete"),
]