# Generated by Django 5.2.7 on 2026-04-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_create_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
