# Generated by Django 5.2.7 on 2026-04-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QaIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('news', 'News'), ('event', 'Event'), ('document', 'Document'), ('project', 'Project'), ('person', 'Person'), ('coach', 'Coach'), ('judge', 'Judge'), ('page', 'Page')], max_length=30)),
                ('source_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('url', models.CharField(blank=True, max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
