# Generated by Django 5.2.7 on 2026-04-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qaindex',
            options={'verbose_name': 'Индекс Q&A', 'verbose_name_plural': 'Индекс Q&A'},
        ),
        migrations.AlterField(
            model_name='qaindex',
            name='source_type',
            field=models.CharField(choices=[('news', 'Новость'), ('project', 'Проект'), ('team_member', 'Игрок'), ('coach', 'Тренер'), ('judge', 'Судья'), ('page', 'Страница')], max_length=30),
        ),
    ]
