# Generated by Django 5.2.7 on 2026-04-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_alter_qaindex_options_alter_qaindex_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaindex',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qaindex',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qaindex',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='qaindex',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='qaindex',
            name='source_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='qaindex',
            name='source_type',
            field=models.CharField(choices=[('news', 'Новость'), ('project', 'Проект'), ('team_member', 'Игрок'), ('coach', 'Тренер'), ('judge', 'Судья'), ('page', 'Страница')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='qaindex',
            index=models.Index(fields=['source_type', 'is_published'], name='qa_qaindex_source__b99e8d_idx'),
        ),
    ]
