# Generated by Django 6.0 on 2026-06-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_qaindex_keywords_qaindex_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaindex',
            name='source_type',
            field=models.CharField(choices=[('news', 'Новость'), ('project', 'Проект'), ('document', 'Документ'), ('document_category', 'Раздел документов'), ('event', 'Событие'), ('media', 'Медиа'), ('person', 'Член федерации'), ('partner', 'Партнер'), ('season', 'Сезон сборной'), ('team_member', 'Игрок'), ('coach', 'Тренер'), ('judge', 'Судья'), ('page', 'Страница')], db_index=True, max_length=30),
        ),
    ]
