# Generated by Django 5.2.7 on 2026-04-04 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_player_id_alter_season_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='coaches/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренера',
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='judges/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Судья',
                'verbose_name_plural': 'Судьи',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('rank', models.CharField(blank=True, max_length=50, verbose_name='Разряд')),
                ('coach', models.CharField(blank=True, max_length=100, verbose_name='Тренер')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Рейтинг')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Фото')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='teams.season', verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Сборный игрок',
                'verbose_name_plural': 'Сборные',
            },
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
