# Generated by Django 5.2.7 on 2026-04-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_coach_judge_teammember_delete_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, null=True, verbose_name='Пол'),
        ),
    ]
