# Generated by Django 5.2.7 on 2026-04-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='show_in_slider',
            field=models.BooleanField(default=False, help_text='Отметьте, если эта новость должна отображаться в слайдере на главной', verbose_name='Показать в слайдере'),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
