# Generated by Django 5.2.7 on 2026-04-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_alter_person_id_alter_subdivision_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='subdivisions',
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['sort_order'], 'verbose_name': 'Член федерации', 'verbose_name_plural': 'Члены федерации'},
        ),
        migrations.AddField(
            model_name='person',
            name='group',
            field=models.CharField(choices=[('board', 'Попечительский совет'), ('members', 'Члены федерации')], default='members', max_length=50, verbose_name='Группа'),
        ),
        migrations.DeleteModel(
            name='Subdivision',
        ),
    ]
