# Generated by Django 5.2.7 on 2026-04-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_remove_person_subdivisions_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='group',
            field=models.CharField(choices=[('board', 'Попечительский совет'), ('members', 'Члены федерации'), ('other', 'Другое')], default='members', max_length=50, verbose_name='Группа'),
        ),
    ]
