# Generated by Django 5.2.7 on 2026-04-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_alter_person_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Член федерации', 'verbose_name_plural': 'Члены федерации'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='period',
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='person',
            name='sort_order',
        ),
    ]
