# Generated by Django 5.2.7 on 2026-04-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaPhoto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaevent',
            options={'ordering': ['-date'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Медиа'},
        ),
        migrations.AlterField(
            model_name='mediaevent',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='mediaphoto',
            name='image',
            field=models.ImageField(upload_to='media/photos/', verbose_name='Фото'),
        ),
    ]
